### ISSUE TITLE
Does not work with "type": "module" in package.json

### ISSUE THREAD

**Issue by SirJosh3917** [swc-project/swc-node#120]
`node -r @swc-node/register index.ts` seems to work, but only if `"type": "module"` isn't in package.json. I would give more details, but I don't know what the problem is myself.

[Attached is a reproducible example of this bug.](https://github.com/Brooooooklyn/swc-node/files/5344521/repro.zip)

**Comment by Brooooooklyn** [comment]
Have you tried change `module` field in `tsconfig.json` to `esnext`?

**Comment by zaboco** [comment]
I have the same issue. And it also reproduces with `module: esnext` in tsconfig.json.

**Comment by fregante** [comment]
Related `ts-node` issue, might have more info https://github.com/TypeStrong/ts-node/issues/1007

**Comment by thelinuxlich** [comment]
might need a `--loader swc-node/esm`?

**Comment by purple-cmd** [comment]
same problem :(

**Comment by janus-reith** [comment]
ts-node added swc support, and supports node ESM using a loader.

However, I have yet to find some way to get Jest tests running with native node ESM, which neither @swc/jest nor ts-node seem to cover...
