### ISSUE TITLE
@swc-node/jest ReferenceError: React is not defined

### ISSUE THREAD

**Issue by chhschou** [swc-project/swc-node#635]
EDIT: I don't think react runtime is supported by `@swc-node` at all.`@swc-node/loader` works in webpack but the bundle produced does not have the react runtime.

Below is the original issue:

my project was using `@swc/jest` and a `.swcrc` like this and jest works fine:
```
{
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "tsx": true,
            "dynamicImport": true,
            "privateMethod": true,
            "functionBind": true,
            "exportDefaultFrom": true,
            "exportNamespaceFrom": true,
            "decorators": true,
            "decoratorsBeforeExport": true,
            "topLevelAwait": true,
            "importMeta": true
        },
        "transform": {
            "react": {
                "runtime": "automatic"
            }
        },
        "target": "es5",
        "loose": false,
        "externalHelpers": false,
        "keepClassNames": false
    }
}
```

I want to move to `@swc-node/jest` since I already have a `tsconfig.json` and I don't see a need to maintain both the `.swcrc` and `tsconfig.json`. 
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "noFallthroughCasesInSwitch": true,
    "suppressImplicitAnyIndexErrors": true,
    "noImplicitAny": false,
    "sourceMap": true,
  },
  "include": [
    "src"
  ]
}
```

I changed jest config from `"^.+\\.(t|j)sx?$": "@swc/jest",` to `"^.+\\.(t|j)sx?$": "@swc-node/jest",` and got error `ReferenceError: React is not defined`. I copied the configs in `.swcrc` from above into jest config and still got the same error. It seems the react runtime configuration is not applied by `@swc-node/jest` but am applied by `@swc/jest`?

**Comment by Gabb-c** [comment]
I'm building my react lib with Rollup, and just using @swc/jest for the tests:

```js
const config = {
...config,
  transform: {
    '^.+\\.(t|j)sx?$': [
      '@swc/jest',
      {
        jsc: {
          transform: {
            react: {
              runtime: 'automatic',
            },
          },
        },
      },
    ],
  },
};
```
So there's no need to have a `.swcrc` in this case.
[Reference](https://github.com/Gabb-c/spotify-embed/blob/8b7b088fab0ed0de3620d9d328babd9b0b3accd1/jest.config.js#L12)

**Comment by havenchyk** [comment]
@Gabb-c can you please clarify how to add a plugin in this config? E.g. I want to use this one https://www.npmjs.com/package/swc-plugin-transform-import

**Comment by AndrewSouthpaw** [comment]
https://github.com/swc-project/swc-node/issues/635#issuecomment-1070766669 was key for me. For some reason it didn't work in `.swcrc` but worked fine when passed directly into the jest config. 🤷🏼‍♂️

**Comment by erfanium** [comment]
What about a Node.js app that is using [nano_-jsx](https://github.com/nanojsx/nano) to render tsx files?

This is my current tsconfig
```json
{
  "extends": "@tsconfig/node16/tsconfig.json",
  "compilerOptions": {
    "jsx": "react",
    "jsxFactory": "h",
    "jsxFragmentFactory": "Fragment",
    "strict": true,
    "baseUrl": ".",
    "lib": [
      "es2022"
    ],
    "target": "es2022",
    "noImplicitAny": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "module": "commonjs",
    "allowJs": true,
    "checkJs": false,
    "importsNotUsedAsValues": "remove",
    "outDir": "./out"
  },
  "include": [
    "."
  ],
  "ts-node": {
    // It is faster to skip typechecking.
    // Remove if you want ts-node to do typechecking.
    "transpileOnly": true,
    "files": true,
    "swc": true,
  },
}

```
