### ISSUE TITLE
Sourcemaps are broken for @swc-node/register/esm

### ISSUE THREAD

**Issue by jwalton** [swc-project/swc-node#719]
index.ts:

```ts
function main() {

    // Some whitespace for swc to optimize away...


    console.log('hello world');
    throw new Error('foo');
}

main()
```

@swc-node/register gives us sourcemap support:

```sh
$ node -r @swc-node/register ./index.ts
hello world
/Users/jwalton/t/index.ts:4
    throw new Error('foo');
    ^

Error: foo
    at main (/Users/jwalton/t/index.ts:7:11)
```

But @swc-node/register/esm does not:

```sh
node --loader @swc-node/register/esm ./index.ts
(node:81567) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
hello world
file:///Users/jwalton/t/index.ts.mjs:3
    throw new Error('foo');
          ^

Error: foo
    at main (file:///Users/jwalton/t/index.ts.mjs:3:11)
```

**Comment by arimgibson** [comment]
I believe I might be having the same issue as I'm having trouble using Node's debugger (through VSCode) with the ESM loader, but it works fine with the standard loader.

**Comment by Xinkai** [comment]
This finally bothered me enough so I took a look.

**Finding:**
Unlike https://github.com/swc-project/swc-node/blob/e34f006484d89c53dd4cac7cface3c4d70841e34/packages/register/register.ts#L115, [esm.mts](https://github.com/swc-project/swc-node/blob/e34f006484d89c53dd4cac7cface3c4d70841e34/packages/register/esm.mts) does not call the `installSourceMapSupport` to enable source map support.

I then tried adding the following in `esm.mts`, as documented at https://nodejs.org/docs/latest-v20.x/api/module.html#initialize. Sadly, it does not work.
```typescript
export async function initialize() {
    console.log("This function is indeed called without error, but source map does not apply");
    installSourceMapSupport();
}
```

**Solution:**
I finally found this to be working (tested on Node 20). https://nodejs.org/docs/latest-v20.x/api/module.html#source-map-v3-support.
```shell
$ node --enable-source-maps --loader @swc-node/register/esm index.ts
```

**Comment by dsyddall** [comment]
Both the CJS and ESM stack traces seem to be incorrect. In @jwalton's report, the CJS stack trace reports an error thrown at line 4 when it should report being thrown at line 7. The only way I have been able to work around this in CJS was to prevent `source-map-support` from being loaded and use Node's `--enable-source-maps` instead.

**Comment by slavafomin** [comment]
Yep, stumbled upon this too.

@Xinkai thank you for a great workaround.

Happy new year :)
