### ISSUE TITLE
Using `@swc/core` version `1.3.85` crashes

### ISSUE THREAD

**Issue by biro456** [swc-project/swc-node#732]
I'm using Node `20.7.0` and calling my script like this:
```shell
node --loader @swc-node/register/esm ./script.js
```

When running with `@swc/core` version `>=1.3.85` I get this error everytime.
```
[Error: unknown field `noInterop`, expected `resolveFully` at line 1 column 548] {
  code: 'InvalidArg'
}
```

If I use `<=1.3.84` it works, so I went to `@swc/core` to investigate, and it seems `1.3.85` added this `resolveFully` option in several places, but `noInterop` was not removed.

**Comment by kdy1** [comment]
`noInterop` should not be accepted, but it did because the `Es6` variant was a unit type.

**Comment by Yovach** [comment]
Do you plan to update `swc-node` to fix this issue ?
