### ISSUE TITLE
TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING] <file> needs an import attribute of type "json"

### ISSUE THREAD

**Issue by MisterJimson** [swc-project/swc-node#757]
I get the above error when importing a JSON file, even though I do use the import attribute.

Both: `import file from './file.json' assert { type: 'json' };` and `import file from './file.json' with { type: 'json' };`

With is the newer syntax but both should be supported.

**Comment by yeliex** [comment]
please provide a minimal reproduction
