### ISSUE TITLE
SWC does not transpile on Windows if tsconfig.json is present in cwd where the cmd is ran

### ISSUE THREAD

**Issue by c3cris** [swc-project/swc-node#758]
### Files
test.ts
`const hello : string = "World";`
tsconfig.json  ( even empty file )
`{}`

### Libs and Versions
tested with
`@swc-node/register: 1.6 or 1.8 as well`
and with node `18.17 and 20.11`

### Reproduce
run command
` node --loader @swc-node/register/esm .\test.ts`
What happens:
```
const hello : string = "World";
      ^^^^^
SyntaxError: Missing initializer in const declaration
```
Expected:
`no errors`

### Remove `tsconfig.json` file and run the command again
` node --loader @swc-node/register/esm .\test.ts`

Result:
`no errors`

### Side note
If you have the test.js and tsconfig.json file in a subfolder and run the command from parent folder where tsconfig.json is not present it will run.
```
pwd = testproject
src
|--- test.ts
|---tsconfig.json
```
It works if you run the command from one directory up if `tsconfig.json` isn't present in the folder you run the cmd
` node --loader @swc-node/register/esm .\src\test.ts`
Result:
`no errors`

**Comment by c3cris** [comment]
I think this might be relevant https://github.com/swc-project/swc/issues/8639

**Comment by yeliex** [comment]
#754  should fixed this. please test and feedback

**Comment by c3cris** [comment]
Ok, I will, thank you.
