### ISSUE TITLE
Unable to import .js files with matching .d.ts files using `@swc-node/register`

### ISSUE THREAD

**Issue by maxburs** [swc-project/swc-node#775]
<img width="616" alt="image" src="https://github.com/swc-project/swc-node/assets/8890312/ca4c0ed0-9970-474a-ac5f-61ae4b0e693d">

Script
```ts
import { test } from "./test.js"; // from "./test"; also fails
test();
```

test.js
```js
export function test() {
  console.log("foo");
}
```

test.d.ts
```ts
export declare function test(): void;
```

The package in this[^1] repro reproduces it with the "cantImportJsFile" npm script.

[^1]: https://github.com/maxburs/swc-node

**Comment by Brooooooklyn** [comment]
@yeliex it seems the `ts.resolveModuleName` resolves `x.d.ts` rather than the `x.js`, can you please take a look?

My suggestion is replace the `ts.resolveModuleName` with the `https://github.com/oxc-project/oxc-resolver`

**Comment by yeliex** [comment]
@Brooooooklyn I would take time to deal with it next week. Sorry for being so busy recently
