### ISSUE TITLE
Can't run a TypeScript project with `.js` and `.d.ts` files in @swc-node/register@1.9.2

### ISSUE THREAD

**Issue by Yovach** [swc-project/swc-node#787]
![image](https://github.com/swc-project/swc-node/assets/31007601/8e5f47f3-307f-4bdb-87eb-cee0f7d74d28)

I updated to @swc-node/register@1.9.2 but I'm still having the following issue https://github.com/swc-project/swc-node/issues/775

My project is using Drizzle with TypeScript. I'll provide a minimal reproduction soon.

**Comment by yeliex** [comment]
fixed in 1.10.0
