### ISSUE TITLE
need help building example, esmregister + esmock

### ISSUE THREAD

**Issue by iambumblehead** [swc-project/swc-node#788]
[When trying to create an example test](https://github.com/iambumblehead/esmock/blob/main/tests/tests-FAIL-swc/package.json#L15) with swc and esmock, this error occurs around the types definition file,
```bash
node --import @swc-node/register/esm-register --test esmock.node-swc.test.ts

> test:current
> node --import @swc-node/register/esm-register --test esmock.node-swc.test.ts

file:///home/bumble/soft/esmock/src/esmock.d.ts:1
type MockMap = { [specifier: string]: any }
     ^^^^^^^

SyntaxError: Unexpected identifier 'MockMap'
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:169:18)
    at callTranslator (node:internal/modules/esm/loader:272:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:278:30)
```

Thanks in advance for any advice

**Comment by Brooooooklyn** [comment]
Fixed in https://github.com/swc-project/swc-node/pull/798

**Comment by iambumblehead** [comment]
The specific error described at the top of this issue is resolved, however, after updating `@swc-node/register` a new issue is encountered,
```bash
✖ should mock js when using swc (34.125566ms)
  file:///home/bumble/soft/esmock/tests/local/mainUtil.js:2
  import babelGeneratedDoubleDefault from 'babelGeneratedDoubleDefault';
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  SyntaxError: The requested module 'babelGeneratedDoubleDefault' does not provide an export named 'default'
```
The error needs context to be understood but, essentially, `@swc-node/register` encounters an error loading mixed esm/cjs modules.

Slightly difficult to describe the sequence resulting in the error, here is what happens,

 1. 'esmock.node-swc.test.ts' imports '../local/main.js' (esm) [link](https://github.com/iambumblehead/esmock/blob/attempt-enable-swc-tests/tests/tests-swc/esmock.node-swc.test.ts#L10)
 2. '../local/main.js' imports './mainUtil.js' (esm) [link](https://github.com/iambumblehead/esmock/blob/attempt-enable-swc-tests/tests/local/main.js#L13)
 3. 'mainUtil.js' imports 'babelGeneratedDoubleDefault' (cjs) _error_ [link](https://github.com/iambumblehead/esmock/blob/attempt-enable-swc-tests/tests/local/mainUtil.js#L2)
 4. '../package.json' links 'babelGeneratedDoubleDefault' to the local directory package 'babelGeneratedDoubleDefault', [link package.json](https://github.com/iambumblehead/esmock/blob/attempt-enable-swc-tests/tests/package.json#L20)
 5. 'babelGeneratedDoubleDefault' describes a cjs module, [link babelGeneratedDoubleDefault/package.json](https://github.com/iambumblehead/esmock/blob/attempt-enable-swc-tests/tests/local/babelGeneratedDoubleDefault/package.json), [link babelGeneratedDoubleDefault.js](https://github.com/iambumblehead/esmock/blob/attempt-enable-swc-tests/tests/local/babelGeneratedDoubleDefault/babelGeneratedDoubleDefault.js)

The other loaders used in the test suite process the same import tree without error https://github.com/iambumblehead/esmock/tree/attempt-enable-swc-tests/tests

Thank you for reading me

**Comment by Brooooooklyn** [comment]
I've tried [tsx](https://github.com/privatenumber/tsx), it's also throw a error:

```ts
// index.ts
import assert from 'node:assert'
import test from 'node:test'

import babelGeneratedDoubleDefault from './babel-generated-double-default'

await test('import default from babel-generated cjs file', () => {
  assert.equal(babelGeneratedDoubleDefault(), 'default.default')
})

```

`pnpm tsx index.ts`:

![CleanShot 2024-07-08 at 21 37 02@2x](https://github.com/swc-project/swc-node/assets/3468483/85c217d8-8bdf-4bdf-8856-9910fde29c58)

**Comment by iambumblehead** [comment]
```bash
git clone https://github.com/iambumblehead/esm-import-cjs-repro.git
cd esm-import-cjs-repro
npm install
npm run test:node # pass
npm run test:tsx # pass
npm run test:swc # fail
```

**Comment by Brooooooklyn** [comment]
> https://github.com/iambumblehead/esm-import-cjs-repro.git

@iambumblehead this failed because of the peerDependencies are missing, you need to install `@swc/core` and `typescript`, and everything should be fine.

**Comment by iambumblehead** [comment]
after adding `@swc/core` and `typescript` dependencies, tests still fail. Do they need to be declared in a specific way in pacakge.json?

```bash
$ cat package.json | grep dependencies -A 6
  "dependencies": {
    "babelGeneratedDoubleDefault": "file:./babelGeneratedDoubleDefault",
    "typescript": "^5.5.3",
    "@swc-node/register": "1.10.2",
    "@swc/core": "^1.6.13",
    "tsx": "^4.15.5"
  },


$ npm install

added 2 packages, and audited 28 packages in 34s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


$ npm run test:swc

> esm-import-cjs-repro@0.0.1 test:swc
> node --import @swc-node/register/esm-register --test test.swc.test.ts

✖ should import babelGeneratedDoubleDefault, cjs deep (12.353619ms)
  file:///home/bumble/soft/esm-import-cjs-repro/src/esmmain2.js:1
  import babelGeneratedDoubleDefault from 'babelGeneratedDoubleDefault';
```

**Comment by iambumblehead** [comment]
the first test, importing mixed esm cjs tree passes, but [the second test](https://github.com/iambumblehead/esmock/blob/attempt-enable-swc-tests/tests/tests-swc/esmock.node-swc.test.ts#L19-L27) encounters a runtime error,
```javascript
test('should mock ts when using swc', async () => {
  const main = await esmock('../local/main-ts.ts', {
    path: {
      basename: () => 'hellow'
    }
  })

  assert.strictEqual(main.pathbasenamewrap(), 'hellow')
})
```

The error occurs when the typescript file "main-ts.ts" is loaded.
```bash
test at esmock.node-swc.test.ts:15:1
✖ should mock ts when using swc (5.206873ms)
  SyntaxError [Error]: Unexpected token ':'
```

_main-ts.ts,_ [link](https://github.com/iambumblehead/esmock/blob/attempt-enable-swc-tests/tests/local/main-ts.ts)
```typescript
import path from 'path'
import pg from 'pg'

export default {
  pathbasenamewrap: (n: any) => path.basename(n),
  pgpoolwrap: (n: any) => pg.Pool(n)
}
```

If the typescript `: any` is removed from the file, the test passes. It seems the file is not transformed.

**Comment by iambumblehead** [comment]
could not reproduce this in the smaller `esm-import-cjs-repro` files. Will try to reproduce there tomorrow maybe.

**Comment by iambumblehead** [comment]
the error happens when esmock is engaged to load the ts file `await esmock('../local/main-ts.ts')` using import does not result in an error `await import ('../local/main-ts.ts')`

the same test using esmock passes when using node-ts, tsx or tsm

**Comment by iambumblehead** [comment]
At esm-import-cjs-repro, the [test is added for tsx and swc](https://github.com/iambumblehead/esm-import-cjs-repro/commit/4fb6be8ca16565b5b6b032ec5b6e4ce8270c40a5) and the error is reproduced using swc
```
git clone https://github.com/iambumblehead/esm-import-cjs-repro.git
cd esm-import-cjs-repro
npm install
npm run test:node # pass
npm run test:tsx # pass
npm run test:swc # fail
```

**Comment by iambumblehead** [comment]
related https://github.com/swc-project/swc-node/issues/710

**Comment by iambumblehead** [comment]
all tests pass :)
