### ISSUE TITLE
@swc-node/core 1.13.3 There is a problem because a keepImportAttributes field is added

### ISSUE THREAD

**Issue by MaYiFanGitHub** [swc-project/swc-node#819]
**error message**
<img width="1071" alt="image" src="https://github.com/user-attachments/assets/4190b31b-ef83-4261-b53f-5c1449711387">

**debugging information**

The first screenshot
<img width="1239" alt="image" src="https://github.com/user-attachments/assets/285f67a6-7979-4a70-b73c-44988425fe09">
Second screenshot
<img width="828" alt="image" src="https://github.com/user-attachments/assets/3987ffb9-33c5-4c58-a0ce-5dcaa101777c">
The third screenshot
<img width="1203" alt="image" src="https://github.com/user-attachments/assets/c82a7575-f0f9-4ff8-82f2-ed1230ce99e8">

**Comment by Brooooooklyn** [comment]
@MaYiFanGitHub you need to upgrade `@swc/core`
